import test from 'node:test';
import assert from 'node:assert/strict';
import { Store, passwordHash } from './store.js';
import { createRecord, transition, recordFor, duplicates, defaults } from './workflow.js';
import { transfer } from './constant-contact.js';
import { makeApp, purgeImages } from './app.js';
import { parseOCRText } from '../services/cardParser.js';
import { extractImage } from './ocr.js';
const assistant={tenant:'alpha',id:'a',role:'assistant'};const reviewer={tenant:'alpha',id:'r',role:'reviewer'};
const fixture=()=>new Store(':memory:','a'.repeat(64));
const input=(email='fiction@example.com')=>({fullName:'Alice Example',companyName:'Fictional Air',email,phone:'+44 20 7946 0000',fictional:true});
function approved(s,email){const r=createRecord(s,assistant,input(email));transition(s,assistant,r.id,'submit',r.version);let current=s.get('alpha','record',r.id);return transition(s,reviewer,r.id,current.status==='possible_duplicate'?'distinct':'approve',current.version);}
function config(s){s.put('alpha','config','cc',{listId:'list',sourceFieldId:'field',testAccountConfirmed:true});}
test('approval is a reviewer decision and submitted records cannot be approved by assistant',()=>{const s=fixture(),r=createRecord(s,assistant,input());transition(s,assistant,r.id,'submit',r.version);assert.throws(()=>transition(s,assistant,r.id,'approve',2),/FORBIDDEN/);assert.equal(transition(s,reviewer,r.id,'approve',2).status,'approved');s.db.close();});
test('tenant isolation and assistant ownership',()=>{const s=fixture(),r=createRecord(s,assistant,input());assert.throws(()=>recordFor(s,{...reviewer,tenant:'beta'},r.id),/NOT_FOUND/);assert.throws(()=>recordFor(s,{...assistant,id:'other'},r.id),/NOT_FOUND/);s.db.close();});
test('duplicates normalize email and international phone without merging',()=>{const s=fixture(),r=createRecord(s,assistant,input());const second=createRecord(s,assistant,{...input('FICTION@example.com'),phone:'0044 (20) 7946-0000'});assert.equal(duplicates(s.all('alpha','record'),second).length,1);assert.equal(transition(s,assistant,second.id,'submit',1).status,'possible_duplicate');assert.throws(()=>transition(s,reviewer,second.id,'approve',2),/DUPLICATE/);assert.equal(s.all('alpha','record').length,2);assert.equal(s.get('alpha','record',r.id).status,'draft');s.db.close();});
test('stale approval rejected and correction returns to editable draft',()=>{const s=fixture(),r=createRecord(s,assistant,input());transition(s,assistant,r.id,'submit',1);assert.throws(()=>transition(s,reviewer,r.id,'approve',1),/STALE/);assert.equal(transition(s,reviewer,r.id,'correct',2).status,'draft');s.db.close();});
test('transfer requires approval; repeat success produces one remote creation',async()=>{const s=fixture();config(s);let calls=0;const cc={lookup:async()=>[],create:async()=>{calls++;return {contact_id:'remote-1'};}};const draft=createRecord(s,assistant,input());await assert.rejects(transfer(s,cc,reviewer,draft.id),/NOT_APPROVED/);const r=approved(s,'other@example.com');assert.equal((await transfer(s,cc,reviewer,r.id)).status,'transferred');await transfer(s,cc,reviewer,r.id);assert.equal(calls,1);s.db.close();});
test('remote duplicate is shown without overwriting',async()=>{const s=fixture();config(s);const r=approved(s);const out=await transfer(s,{lookup:async()=>[{contact_id:'existing'}],create:()=>assert.fail()},reviewer,r.id);assert.equal(out.status,'possible_duplicate');assert.equal(out.remoteMatches[0].contact_id,'existing');s.db.close();});
test('timeout is visible and cannot be blindly retried',async()=>{const s=fixture();config(s);const r=approved(s);const cc={lookup:async()=>[],create:async()=>{throw new Error('sensitive payload must not escape');}};const out=await transfer(s,cc,reviewer,r.id);assert.equal(out.status,'transfer_failed');assert.equal(out.uncertain,true);assert.equal(out.errorCode,'CC_NETWORK_FAILURE');await assert.rejects(transfer(s,cc,reviewer,r.id),/RECONCILIATION/);s.db.close();});
test('429 persists cooldown and allows a later retry',async()=>{const s=fixture();config(s);const r=approved(s);const cc={lookup:async()=>[],create:async()=>{throw Object.assign(new Error(),{httpStatus:429,code:'CC_RATE_LIMIT',retryAfter:120});}};const out=await transfer(s,cc,reviewer,r.id);assert.equal(out.uncertain,false);await assert.rejects(transfer(s,cc,reviewer,r.id),/RETRY_NOT_DUE/);out.retryAt=0;s.put('alpha','record',r.id,out);assert.equal((await transfer(s,{lookup:async()=>[],create:async()=>({contact_id:'later'})},reviewer,r.id)).status,'transferred');s.db.close();});
test('concurrent transfers are serialized',async()=>{const s=fixture();config(s);const r=approved(s);let release;const wait=new Promise(resolve=>release=resolve);const first=transfer(s,{lookup:async()=>{await wait;return [];},create:async()=>({contact_id:'one'})},reviewer,r.id);await assert.rejects(transfer(s,{},reviewer,r.id),/BUSY/);release();await first;s.db.close();});
test('retention deletes images and emits non-PII audit records',()=>{const s=fixture();s.put('alpha','image','image',{id:'image',recordId:'record',expiresAt:1,content:'secret'});assert.equal(purgeImages(s,2),1);assert.equal(s.get('alpha','image','image'),null);const audit=s.db.prepare('SELECT * FROM audit').get();assert.equal(audit.action,'image_deleted');assert.ok(!JSON.stringify(audit).includes('secret'));s.db.close();});
test('database payloads encrypted and wrong key fails',()=>{const s=fixture();createRecord(s,assistant,input());const payload=s.db.prepare('SELECT payload FROM entities').get().payload;assert.ok(!payload.includes('Alice'));s.key=Buffer.alloc(32);assert.throws(()=>s.open(payload));s.db.close();});
test('unknown/sensitive fields and dropdown values rejected',()=>{const s=fixture();assert.throws(()=>createRecord(s,assistant,{...input(),religion:'x'}));assert.throws(()=>createRecord(s,assistant,{...input(),event:'unapproved'}),/DROPDOWN/);s.db.close();});
test('production cannot start',()=>{const s=fixture();assert.throws(()=>makeApp(s,{APP_ENV:'production'}),/locked/);s.db.close();});
test('capture can start empty but incomplete drafts cannot be submitted',()=>{const s=fixture();const r=createRecord(s,assistant,{fictional:true});assert.equal(r.status,'draft');assert.throws(()=>transition(s,assistant,r.id,'submit',r.version),/COMPLETE_NAME_EMAIL/);const second=createRecord(s,assistant,{fictional:true});assert.equal(duplicates(s.all('alpha','record'),second).length,0);s.db.close();});
test('email whitespace and case normalize before duplicate checking',()=>{const s=fixture();const r=createRecord(s,assistant,input('  ALICE@example.com  '));assert.equal(r.data.email,'alice@example.com');s.db.close();});
test('parser preserves international primary phone and avoids substring company matches',()=>{const r=parseOCRText('Alice Example\nSales Manager\nFictional Aviation\ncard@example.com\n+61 2 5550 0100\n+1 202 555 0102');assert.equal(r.fullName,'Alice Example');assert.equal(r.companyName,'Fictional Aviation');assert.equal(r.phone.replace(/\D/g,''),'61255500100');assert.equal(r.alternatePhone.replace(/\D/g,''),'12025550102');});
test('image decoder rejects fake PNG content before OCR',async()=>{await assert.rejects(extractImage(Buffer.from([137,80,78,71,13,10,26,10,0,0]),{OCR_PROVIDER:'local'}));});
test('HTTP authentication, CSRF, support limits, revocation and safe errors',async()=>{
 const s=fixture();for(const [id,role] of [['admin','admin'],['helper','support']])s.put('alpha','user',id,{id,username:id,role,active:true,password:passwordHash('LongFictionalPassword!'),expiresAt:Date.now()+60000});
 const app=makeApp(s,{APP_ORIGIN:'http://localhost'});const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));const base=`http://127.0.0.1:${server.address().port}`;
 try{assert.equal((await fetch(base+'/api/pilot/records')).status,401);const login=async username=>{const r=await fetch(base+'/api/pilot/login',{method:'POST',headers:{Origin:'http://localhost','Content-Type':'application/json'},body:JSON.stringify({tenant:'alpha',username,password:'LongFictionalPassword!'})});return {cookie:r.headers.get('set-cookie').split(';')[0],...(await r.json())};};
 const admin=await login('admin'),support=await login('helper');assert.equal((await fetch(base+'/api/pilot/records',{headers:{Cookie:support.cookie}})).status,403);assert.equal((await fetch(base+'/api/pilot/metrics',{headers:{Cookie:support.cookie}})).status,200);
 assert.equal((await fetch(base+'/api/pilot/config',{method:'PUT',headers:{Cookie:admin.cookie,Origin:'http://localhost','Content-Type':'application/json'},body:JSON.stringify(defaults)})).status,403);
 assert.equal((await fetch(base+'/api/pilot/users/helper/revoke',{method:'POST',headers:{Cookie:admin.cookie,Origin:'http://localhost','x-csrf-token':admin.csrf,'Content-Type':'application/json'},body:'{}'})).status,200);
 assert.equal((await fetch(base+'/api/pilot/metrics',{headers:{Cookie:support.cookie}})).status,401);
 }finally{await new Promise(resolve=>server.close(resolve));s.db.close();}
});
